### ISSUE TITLE
Possible to cycle inputs with MSI GD?

### ISSUE THREAD

**Issue by Skyyblaze** [couriersud/msigd#21]
I'm on Windows and use MSI GD to switch input sources and load a profile at the same time. Currently I need to dedicate two macro-keys on my Logitech G815 keyboard to achieve this.

One key sends:

msigd.exe --game_mode user --input dp

while the other sends:

msigd.exe --game_mode rts --input hdmi2

which works great, although I wonder, could I somehow consolidate this to only use one key for it? So if the monitor is currently on DP input it will switch to HDMI 2 and vice-versa.

**Comment by couriersud** [comment]
You will need a batch file/script to achieve the task. This script would use msigd to query the game_mode and based on the game_mode send one of the two commands above.
